issue 85/PR 212034: configuration files on linux
follows the agreed-on design that supports two usage models: one for
one-step temp-config-and-run, and one for two-step config and run.  

hierarchy in precedence order:
1) <local>/appname.<pid>.1config{32,64}
2) <local>/appname.config{32,64}       
3) <local>/default.0config{32,64}      
4) <global>/appname.config{32,64}      
5) <global>/default.0config{32,64}     
6) env vars                            

within local and within global, default will fill in missing values in
app-specific; env vars will fill in any remaining missing values      

code changes:
* added core/config.[ch] used by core and preload that walks the precedence
  order until a config file is located.  it reads the file and then reads  
  env vars to fill in the gaps.  the file is re-read for dynamic option    
  synch.                                                                   
* bumped version to 2.0.0                                                  
* updated docs, including a warning that DYNAMORIO_RUNUNDER must now be set
* linux:                                                                   
  - -follow_children is on by default to match old behavior                
  - propagate DYNAMORIO_RUNUNDER across execve if -follow_children         
    and only propagate DYNAMORIO_OPTIONS and logdir if -follow_children    
  - if we had detach would we want to detach in fork child?                
    seems like on linux following children is meaningful for execve        
    but not as much for fork: going to ignore.                             
* linux tools:                                                             
  - drconfig, drrun, and drinject are all generated from dreploy.in        
  - a drdeploy symlink to drrun for back compat is installed               

backward compat:
* NOT backward compatible if using raw env vars!
  must now set DYNAMORIO_RUNUNDER to 3.         
  FIXME: I don't see any way around this since we do not want to
  take over un-configured children by default: that would require
  explicit RUNUNDER=0 default or specific config files to get the
  default behavior we want.  hopefully most users are using the drdeploy
  script unlike us.  we use raw env for these, which I updated:         
  - spec2k benchmark running via runstats                               
  - test running via runstats                                           

future work:
* i#287/PR 546544: honor DYNAMORIO_AUTOINJECT on linux
* use/support full paths instead of just short app name?              
  going to punt on it until we run into issues from short names       

--------------------------------------------------
also includes the Windows side which is off-by-default because the
tools are not yet converted:                                      

issue 265/PR 486139: eliminate need for admin privileges to run Dr. Memory on Windows

Windows support brought up the following issues:

* 32 vs 64: different AUTOINJECT, pcache dirs, and options too since will
  have client path: more complex to have each parameter come in flavors  
  like AUTOINJECT{32,64} so changing name of .config to .config{32,64}.  
  enough apps have same name in both flavors to be worth splitting.      

* added support for default.0config{32,64} file filling in unspecified
  values in app config file to match the specific-global hierarchy that
  Windows has in the registry.  however, global will not fill in local, if
  any local file exists.                                                  

* support old method of all params in registry:
  new cmake option and #define PARAMS_IN_REGISTRY

* support reading config file for another app name, used in injector and
  following children



SVN-Revision: 303

diff --git a/tools/drdeploy.in b/tools/drdeploy.in
--- a/tools/drdeploy.in
+++ b/tools/drdeploy.in
@@ -35,24 +35,24 @@
 
 ###########################################################################
 ##
-## DynamoRIO injector script for Linux
+## DynamoRIO @name@ script for Linux
 ## 
-## usage: drdeploy [-v] [-debug] [-dr_home <path>] [-ops <dr_options>]
+## usage: @name@ [-v] [-debug] [-dr_home <path>] [-ops <dr_options>]
 ##                 [-logdir <path>] -client <path> <executable> [args ...]
 ##
 ##  [-v]                   Verbose output
 ##  [-debug]               Use debug build of DynamoRIO (release is default)
-##  [-64]                  Use 64-bit DynamoRIO (default is 32-bit).  This
+##  [-@archother@]                  Use @archother@-bit DynamoRIO (default is @archdefault@-bit).  This
 ##                           should match what the client library and executable
 ##                           being run were compiled for.
 ##  [-dr_home <path>]      Path to the DynamoRIO install.
-##                           Defaults to .. from drdeploy; may also be omitted
+##                           Defaults to .. from @name@; may also be omitted
 ##                           if DYNAMORIO_HOME is defined in the environment.
 ##  [-ops <dr_options>]    DynamoRIO options (such as -stderr_mask 0xc
 ##                           or -opt_memory: see docs). Can also be specified
 ##                           with DYNAMORIO_OPTIONS in the environment.
 ##  [-logdir <path>]       Path to logging directory.  Defaults to ../logs from
-##                           drdeploy; may also be omitted if DYNAMORIO_LOGDIR
+##                           @name@; may also be omitted if DYNAMORIO_LOGDIR
 ##                           is defined in the environment.
 ##  [-client <path> <ID> "<options>"]
 ##                         Register one or more clients to run alongside DR.
@@ -65,11 +65,16 @@
 ##                           this case, clients specified first on the command
 ##                           line have higher priority.  Neither the path nor
 ##                           the options may contain semicolon characters.
-##  <executable> [args...] The executable to run under DynamoRIO and the args
-##                           to pass to it.
+##  <executable> [args...] The executable to run under DynamoRIO (and the args
+##                           to pass to it if running now).
 
 lib=release
 arch=@archdefault@
+# drconfig: config=1, runapp=0
+# drrun: config=1, runapp=1
+# drinject: config=0, runapp=1
+config=@config@
+runapp=@runapp@
 
 usage="usage: $0 [-v] [-debug] [-32] [-64] [-dr_home <path>] [-ops <dr_options>] [-logdir <path>] [-client <path> <ID> \"<options>\"]* <executable> [args ...]"
 
@@ -234,16 +239,61 @@ else
     export DYNAMORIO_OPTIONS="${client_op_string} $DYNAMORIO_OPTIONS"
 fi
 
-if [ "$verbose" = "yes" ]
+# i#85/PR 212034: we now use config files
+
+if [ ! -n "$HOME" ]
 then
-    echo "Using $lib DynamoRIO ($dr_lib_path/$lib/libdynamorio.so)"
-    echo "With DynamoRIO options=\"$DYNAMORIO_OPTIONS\""
-    echo "Using logging directory=\"$DYNAMORIO_LOGDIR\""
-    echo "Running \"$*\""
+    echo "ERROR - $HOME must exist"
+    echo $usage
+    exit
+fi
+cfgdir="$HOME/.dynamorio"
+if [ ! -d $cfgdir ]
+then
+    mkdir -p "$cfgdir"
 fi
 
-export LD_LIBRARY_PATH=$dr_lib_path/$lib:$LD_LIBRARY_PATH
-export LD_PRELOAD="libdynamorio.so libdrpreload.so"
+app="$1"
+shift
+# better to require bash and use ${app##*/}?
+name=`basename $app`
 
-# keep same pid for easier scripting
-exec $*
+if [ "$config" = "1" ]
+then
+    if [ "$runapp" = "1" ]
+    then
+        cfgfile="$cfgdir/$name.$$.1config$arch"
+        echo "# one-time config file" > $cfgfile
+        if [ "$verbose" = "yes" ]
+        then
+            echo "Using $lib DynamoRIO ($dr_lib_path/$lib/libdynamorio.so)"
+            echo "With DynamoRIO options=\"$DYNAMORIO_OPTIONS\""
+            echo "Using logging directory=\"$DYNAMORIO_LOGDIR\""
+            echo "Running \"$app $*\""
+        fi
+    else
+        cfgfile="$cfgdir/$name.config$arch"
+        echo "# DynamoRIO config file" > $cfgfile
+    fi
+    echo "DYNAMORIO_RUNUNDER=1" >> $cfgfile
+    echo "DYNAMORIO_OPTIONS=$DYNAMORIO_OPTIONS" >> $cfgfile
+    echo "DYNAMORIO_LOGDIR=$DYNAMORIO_LOGDIR" >> $cfgfile
+    echo "DYNAMORIO_AUTOINJECT=$dr_lib_path/$lib/libdynamorio.so" >> $cfgfile
+    echo "DYNAMORIO_HOME=$dr_lib_path" >> $cfgfile
+fi
+
+if [ "$runapp" = "1" ]
+then
+    export LD_LIBRARY_PATH=$dr_lib_path/$lib:$LD_LIBRARY_PATH
+    export LD_PRELOAD="libdynamorio.so libdrpreload.so"
+    
+    # keep same pid for easier scripting
+    exec $app $*
+else
+    if [ "$verbose" = "yes" ]
+    then
+        echo "Wrote config file $cfgfile"
+        exit 0
+    fi
+fi
+exit 1
